Traceback (most recent call last):
  File "/home/dbuchan/Projects/profile_drift/msa_transformer_investigation/esm_seq_generator_single.py", line 325, in <module>
    read_pfam_alignments(sys.argv[2], drift_families, esm2_transformer, esm2_transformer_alphabet)
  File "/home/dbuchan/Projects/profile_drift/msa_transformer_investigation/esm_seq_generator_single.py", line 264, in read_pfam_alignments
    for line in fh:
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 6221: invalid continuation byte
